### ISSUE TITLE
Strange Escape Sequences in Terminal

### ISSUE THREAD

**Issue by knpwrs** [rf/nd#11]
I am trying to use `nd` to view a README file I wrote (see [here](https://github.com/KenPowers/dotfiles/blob/f9758eb1362d7f937e36db8c4c503a3ed5c29824/README.md)) but I just get a bunch of strange output:

![image](https://cloud.githubusercontent.com/assets/174864/7812732/20936024-0383-11e5-9c62-752af3727ad7.png)

I am using `zsh 5.0.5 (x86_64-apple-darwin14.0)` and `node v0.12.3`. Any ideas?

**Comment by knpwrs** [comment]
The file is just ASCII (UTF-8) text:

![image](https://cloud.githubusercontent.com/assets/174864/7812757/611bc2ee-0383-11e5-919c-2825f6bcfa61.png)

**Comment by rf** [comment]
Those are the ansi escape codes that are supposed to make colors and stuff. What is your $PAGER set to? try doing `echo $PAGER`. If it's just `less`, then you should change it to `less -R`, which supports ansi escapes.

**Comment by knpwrs** [comment]
Cool, that worked. I thought I had some default `less` settings but I guess I didn't.

Thanks.
